table _Measures
	lineageTag: 73f36a59-43a8-4c2b-94d3-40a12327b434

	/// Gross line-item revenue calculated as quantity times item price.
	measure 'Total Revenue' = SUM ( 'order_items'[line_revenue] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 6a86a0fb-6537-4da0-86fe-3844a316c857

	/// Total payment amount recorded.
	measure 'Total Payments' = SUM ( 'payments'[amount] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 0da8a430-9476-4363-af12-d840259c1047

	/// Total refunded amount.
	measure 'Total Refund' = SUM ( 'returns'[refund] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 67132baf-f777-45de-bf34-47aeda1e2ea5

	/// Revenue after subtracting refunds.
	measure 'Net Revenue' = [Total Revenue] - [Total Refund]
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 2671f264-e98d-430a-9642-b2e58527ce06

	/// Difference between payment amount and calculated gross revenue.
	measure 'Payment Gap' = [Total Payments] - [Total Revenue]
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 263eb003-5492-44e3-857c-09962c750da5

	/// Average gross revenue per order.
	measure 'Average Order Value' = DIVIDE ( [Total Revenue], [Total Orders] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Revenue
		lineageTag: 2a1529b1-1cc3-488d-9bd4-9435dd15d107

	/// Average promotion discount.
	measure 'Average Discount' = AVERAGE ( 'promotions'[discount] )
		formatString: 0.00%
		displayFolder: Revenue
		lineageTag: 06082f1c-abb6-4e58-91f0-52bff410a786

	/// Distinct order count.
	measure 'Total Orders' = DISTINCTCOUNT ( 'orders'[order_id] )
		formatString: #,0
		displayFolder: Orders
		lineageTag: 228dbdc5-9f4e-4d3d-a846-5218f395e3a5

	/// Total quantity sold.
	measure 'Total Quantity' = SUM ( 'order_items'[qty] )
		formatString: #,0
		displayFolder: Orders
		lineageTag: 173733c0-0180-4c14-87f8-b7572a3812a5

	/// Distinct order item count.
	measure 'Order Item Count' = DISTINCTCOUNT ( 'order_items'[order_item_id] )
		formatString: #,0
		displayFolder: Orders
		lineageTag: de3c713f-c767-42ad-b4f8-aacafa72e781

	/// Average number of line items per order.
	measure 'Items per Order' = DIVIDE ( [Order Item Count], [Total Orders] )
		formatString: #,0.00
		displayFolder: Orders
		lineageTag: 8fc8d7c1-e09e-48af-b259-7f55712fe89b

	/// Distinct customer count.
	measure 'Total Customers' = DISTINCTCOUNT ( 'customers'[customer_id] )
		formatString: #,0
		displayFolder: Customers
		lineageTag: 39d96913-ebdd-4886-a70e-d4f853588145

	/// Average gross revenue per customer.
	measure 'Revenue per Customer' = DIVIDE ( [Total Revenue], [Total Customers] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Customers
		lineageTag: 94aa5532-ea29-425d-93ce-7194da182af5

	/// Distinct return transaction count.
	measure 'Return Count' = DISTINCTCOUNT ( 'returns'[return_id] )
		formatString: #,0
		displayFolder: Returns
		lineageTag: 1d9754bb-7326-49ee-9300-80f0c52d8785

	/// Distinct returned order-item count.
	measure 'Returned Item Count' = DISTINCTCOUNT ( 'returns'[order_item_id] )
		formatString: #,0
		displayFolder: Returns
		lineageTag: 97c99e1e-a5e2-431b-8d57-2ba85a466b36

	/// Share of order items that were returned.
	measure 'Return Rate' = DIVIDE ( [Returned Item Count], [Order Item Count] )
		formatString: 0.00%
		displayFolder: Returns
		lineageTag: 5c0e229d-e34c-4344-9df8-6b4c882fbc82

	/// Average refund value per return.
	measure 'Refund per Return' = DIVIDE ( [Total Refund], [Return Count] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Returns
		lineageTag: 59b0ab36-abf5-4225-9c69-ad64b06b25fa

	/// Distinct shipment count.
	measure 'Shipment Count' = DISTINCTCOUNT ( 'shipments'[shipment_id] )
		formatString: #,0
		displayFolder: Shipments
		lineageTag: 309d2429-28b0-4890-99ff-9eb1dd808134

	/// Shipments with delivered status.
	measure 'Delivered Shipments' = CALCULATE ( [Shipment Count], 'shipments'[status] = "delivered" )
		formatString: #,0
		displayFolder: Shipments
		lineageTag: 806af42d-08ae-4616-99f4-91e2efc855ad

	/// Shipments with shipped status.
	measure 'Shipped Shipments' = CALCULATE ( [Shipment Count], 'shipments'[status] = "shipped" )
		formatString: #,0
		displayFolder: Shipments
		lineageTag: 84b0167b-a35d-44b4-9070-f39c4dec99f8

	/// Shipments with late status.
	measure 'Late Shipments' = CALCULATE ( [Shipment Count], 'shipments'[status] = "late" )
		formatString: #,0
		displayFolder: Shipments
		lineageTag: a07c418c-a288-4329-a4d3-6188f644ecc0

	/// Share of shipments delivered.
	measure 'Delivered Shipment Rate' = DIVIDE ( [Delivered Shipments], [Shipment Count] )
		formatString: 0.00%
		displayFolder: Shipments
		lineageTag: aa11a227-3896-4efb-b6c3-f5f717a88f79

	/// Share of shipments marked late.
	measure 'Late Shipment Rate' = DIVIDE ( [Late Shipments], [Shipment Count] )
		formatString: 0.00%
		displayFolder: Shipments
		lineageTag: 16c6c441-d1a6-49f5-ae8e-b06213b024a8

	/// Distinct store count.
	measure 'Total Stores' = DISTINCTCOUNT ( 'stores'[store_id] )
		formatString: #,0
		displayFolder: Operations
		lineageTag: 4ec80f63-e432-4fd5-91e4-faf780e8f613

	/// Distinct employee count.
	measure 'Total Employees' = DISTINCTCOUNT ( 'employees'[employee_id] )
		formatString: #,0
		displayFolder: Operations
		lineageTag: 6a9d4386-99bd-4e95-b977-753319a4f770

	/// Average employee salary.
	measure 'Average Salary' = AVERAGE ( 'employees'[salary] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Operations
		lineageTag: 18d25fc3-8cc7-4499-91b7-0f4d95092005

	/// Distinct product count.
	measure 'Total Products' = DISTINCTCOUNT ( 'products'[product_id] )
		formatString: #,0
		displayFolder: Operations
		lineageTag: 22397020-8f75-42da-9d1f-f28be71eed81

	/// Distinct category count.
	measure 'Total Categories' = DISTINCTCOUNT ( 'categories'[category_id] )
		formatString: #,0
		displayFolder: Operations
		lineageTag: 607d20b2-5dd1-4813-9e83-3b47e2441c28

	/// Distinct supplier count.
	measure 'Total Suppliers' = DISTINCTCOUNT ( 'suppliers'[supplier_id] )
		formatString: #,0
		displayFolder: Operations
		lineageTag: 8fa5138e-4be0-4f5c-a459-2f5d3745c97d

	/// Gross revenue in the previous month.
	measure 'Revenue Previous Month' = CALCULATE ( [Total Revenue], DATEADD ( 'Date'[Date], -1, MONTH ) )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Time Intelligence
		lineageTag: 613a8526-d40d-48dd-bd56-a33d6d3843cd

	/// Month-over-month revenue change.
	measure 'Revenue MoM Change' = [Total Revenue] - [Revenue Previous Month]
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Time Intelligence
		lineageTag: 5968d65b-2262-4d6c-ac1d-dacfb290f1f4

	/// Month-over-month revenue growth rate.
	measure 'Revenue MoM %' = DIVIDE ( [Revenue MoM Change], [Revenue Previous Month] )
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8d30016f-4bd3-4bd4-9f40-696fae6fe76b

	/// Gross revenue in the same period last year.
	measure 'Revenue Previous Year' = CALCULATE ( [Total Revenue], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Time Intelligence
		lineageTag: 3bfdaf3f-3fdd-4b1d-8309-c49a7a7d5239

	/// Year-over-year revenue change.
	measure 'Revenue YoY Change' = [Total Revenue] - [Revenue Previous Year]
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Time Intelligence
		lineageTag: e6008e27-f686-492b-89df-7b9dc20f955a

	/// Year-over-year revenue growth rate.
	measure 'Revenue YoY %' = DIVIDE ( [Revenue YoY Change], [Revenue Previous Year] )
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 5b0a4e82-8d71-423d-bffd-9cbac894ea7e

	/// Year-to-date gross revenue.
	measure 'Revenue YTD' = TOTALYTD ( [Total Revenue], 'Date'[Date] )
		formatString: $#,0.00;($#,0.00);$0.00
		displayFolder: Time Intelligence
		lineageTag: 6ff248bd-432e-43c5-b1c7-61f4d5f4d9c9

	column 'Measure Group'
		isHidden
		lineageTag: a4f851a9-3c81-4966-b725-77a013455f89
		summarizeBy: none
		isNameInferred
		sourceColumn: [Measure Group]

	partition _Measures = calculated
		mode: import
		source = DATATABLE("Measure Group", STRING, {{"Core"}})

