table categories
	lineageTag: db7a4565-5f1f-4104-af34-03e6916e18f2

	column category_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 8b4b368b-5ea2-49bc-8741-727cf7cefe11
		summarizeBy: none
		sourceColumn: category_id

	column category_name
		dataType: string
		lineageTag: f3a7a3f2-c38c-48b6-93a6-f8343a7254b8
		sourceColumn: category_name

	partition categories = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\categories.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"category_id", Int64.Type}, {"category_name", type text}})
				in
				    #"Changed Type"

