table customers
	lineageTag: 728cc776-ffcd-4836-8d07-27e6610c58b6

	column customer_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 5a032857-f508-4ad1-8a25-37cce036a9eb
		summarizeBy: none
		sourceColumn: customer_id

	column city
		dataType: string
		lineageTag: 9782e0f2-f791-4dba-b30c-90632092e684
		sourceColumn: city

	column signup_date
		dataType: dateTime
		lineageTag: 9564ae56-cfd4-4d44-91e8-147436a6f622
		sourceColumn: signup_date

	column Segment
		dataType: string
		lineageTag: ffcb29fe-a68f-4ff6-81fd-466f7de9cb48
		sourceColumn: Segment

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\customers.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"customer_id", Int64.Type}, {"city", type text}, {"signup_date", type date}, {"Segment", type text}})
				in
				    #"Changed Type"

