table employees
	lineageTag: 3225b471-0a9b-45c3-803e-c6ad0493fc0e

	column employee_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: ac5fc55d-bb4f-424d-8091-340dae645c1e
		summarizeBy: none
		sourceColumn: employee_id

	column store_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: f59ba4fd-3b18-4b3f-9bbb-0bd8786138bd
		summarizeBy: none
		sourceColumn: store_id

	column salary
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: ed8d4fcc-71fd-4b5b-ba18-97f87e5fef72
		summarizeBy: average
		sourceColumn: salary

	partition employees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\employees.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"employee_id", Int64.Type}, {"store_id", Int64.Type}, {"salary", type number}})
				in
				    #"Changed Type"

