table orders
	lineageTag: 05e4f8a5-d9ee-4141-81b2-f0e069830d14

	column order_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 2c592d68-0bfa-4d8a-8c46-c218385aa97b
		summarizeBy: none
		sourceColumn: order_id

	column customer_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: fe9efb4b-71a8-4ea9-8eca-f40ac00cf4ed
		summarizeBy: none
		sourceColumn: customer_id

	column store_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: ae630eab-22da-4ab5-9cd5-22e53a1e9200
		summarizeBy: none
		sourceColumn: store_id

	column order_date
		dataType: dateTime
		lineageTag: a79c84f3-2479-424d-8fdb-ee1ce582d914
		sourceColumn: order_date

	column promotion_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: f61a0b1d-56c4-4634-aef7-37668d4c6a00
		summarizeBy: none
		sourceColumn: promotion_id

	partition orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\orders.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"order_id", Int64.Type}, {"customer_id", Int64.Type}, {"store_id", Int64.Type}, {"order_date", type date}, {"promotion_id", Int64.Type}})
				in
				    #"Changed Type"

