table order_items
	lineageTag: f558ddde-7901-4d37-abbb-77c1a75e2066

	column order_item_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 9624065a-df17-4858-9e85-6fb1b0e21bc7
		summarizeBy: none
		sourceColumn: order_item_id

	column order_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 3b72f3ce-4364-442f-83e1-2b7b6b9c81b3
		summarizeBy: none
		sourceColumn: order_id

	column product_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 890c0a96-de5a-40c3-8ad7-a0ddca2fa447
		summarizeBy: none
		sourceColumn: product_id

	column qty
		dataType: int64
		formatString: #,0
		lineageTag: 94b39688-c40c-410d-b3f5-92935c8fffe6
		summarizeBy: sum
		sourceColumn: qty

	column price
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: b13cbf9f-8bab-48e2-81b7-508de7489a55
		summarizeBy: sum
		sourceColumn: price

	column line_revenue
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: 8b17450d-e49c-41e0-ae0e-40a744e9c559
		summarizeBy: sum
		sourceColumn: line_revenue

	partition order_items = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\order_items.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"order_item_id", Int64.Type}, {"order_id", Int64.Type}, {"product_id", Int64.Type}, {"qty", Int64.Type}, {"price", type number}}),
				    #"Added Line Revenue" = Table.AddColumn(#"Changed Type", "line_revenue", each [qty] * [price], type number)
				in
				    #"Added Line Revenue"

