table payments
	lineageTag: 837bb02a-b7d8-400c-a1c1-8253bafd0327

	column payment_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 26d172cf-a327-4eef-be82-65668da124c8
		summarizeBy: none
		sourceColumn: payment_id

	column order_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 37eae11f-97c2-4245-a66a-7c13066ea205
		summarizeBy: none
		sourceColumn: order_id

	column amount
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: 8d7bdaa5-e306-43ac-a911-61206354d331
		summarizeBy: sum
		sourceColumn: amount

	partition payments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\payments.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"payment_id", Int64.Type}, {"order_id", Int64.Type}, {"amount", type number}})
				in
				    #"Changed Type"

