table products
	lineageTag: 18858c1c-3667-40cf-aa0d-a3c1bf012417

	column product_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 96a560f8-c950-4086-9f54-43edf95f407d
		summarizeBy: none
		sourceColumn: product_id

	column category_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: cd9e50f2-cb2c-47e7-b25a-0f3a4bd8e234
		summarizeBy: none
		sourceColumn: category_id

	column supplier_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 1f842410-8ed1-47a3-bd08-36a1a1ff00b4
		summarizeBy: none
		sourceColumn: supplier_id

	column price
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: 9a0fcd60-f1b9-4876-a6eb-4c07c3c71cc0
		summarizeBy: average
		sourceColumn: price

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\products.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"product_id", Int64.Type}, {"category_id", Int64.Type}, {"supplier_id", Int64.Type}, {"price", type number}})
				in
				    #"Changed Type"

