table promotions
	lineageTag: ff788e55-80f5-4b32-87f2-2f892487ae2c

	column promotion_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: b6a45159-c163-4209-a314-1bcff043f979
		summarizeBy: none
		sourceColumn: promotion_id

	column discount
		dataType: decimal
		formatString: 0.00%
		lineageTag: 009b3672-4c7c-4b0e-a809-ac2de06eee4e
		summarizeBy: average
		sourceColumn: discount

	partition promotions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\promotions.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"promotion_id", Int64.Type}, {"discount", type number}})
				in
				    #"Changed Type"

