table returns
	lineageTag: d67e27ae-b5fd-4eb3-aa20-ee58afb0863f

	column return_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: ec340798-a49c-431d-b6dc-321c0a09bd31
		summarizeBy: none
		sourceColumn: return_id

	column order_item_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 394964d1-7abc-40a3-afaa-76c82a8ba951
		summarizeBy: none
		sourceColumn: order_item_id

	column refund
		dataType: decimal
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: 28fe7e7e-b74a-4973-9543-0a2d2f7f6cad
		summarizeBy: sum
		sourceColumn: refund

	partition returns = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\returns.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"return_id", Int64.Type}, {"order_item_id", Int64.Type}, {"refund", type number}})
				in
				    #"Changed Type"

