table shipments
	lineageTag: a52118cc-78fe-4cbc-8d43-b438588e515d

	column shipment_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: e3c4b10c-5551-4d6d-a38a-fcf7aa25e74e
		summarizeBy: none
		sourceColumn: shipment_id

	column order_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 4328cd9c-a2bb-40ab-ba15-067ebd7c26e4
		summarizeBy: none
		sourceColumn: order_id

	column status
		dataType: string
		lineageTag: 00cf1b05-a037-41fb-b188-be0c33ad4fa8
		sourceColumn: status

	partition shipments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\shipments.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"shipment_id", Int64.Type}, {"order_id", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

