table stores
	lineageTag: f1383546-6e5c-49f5-b467-9cf4b4322e5e

	column store_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: eb85e583-c662-43b4-8c41-f36798fb0317
		summarizeBy: none
		sourceColumn: store_id

	column city
		dataType: string
		lineageTag: dc34fc85-6394-45be-bceb-1c1ed054c1dc
		sourceColumn: city

	partition stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\stores.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"store_id", Int64.Type}, {"city", type text}})
				in
				    #"Changed Type"

