table suppliers
	lineageTag: b4735ae4-94b6-43c4-87b9-3f51244d9f46

	column supplier_id
		dataType: int64
		isHidden
		isNullable: false
		lineageTag: 6a00b08b-f86a-45c8-94ee-a3290dc7b3c3
		summarizeBy: none
		sourceColumn: supplier_id

	column country
		dataType: string
		lineageTag: 9ca03119-ae41-420c-9dc7-9dc25f068951
		sourceColumn: country

	partition suppliers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\\School\\DV\\dv-lab3-dashboard\\data\\cleaned\\suppliers.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"supplier_id", Int64.Type}, {"country", type text}})
				in
				    #"Changed Type"

